timeout: 1
command_cards:
  403: command-pause
  404: command-continue
  405: command-cancel-active-task
  406: command-cancel-all-tasks
  407: move-look-straight
  408: move-look-at-me
  409: move-tuck-arm
  410: move-arm-home-position
  411: move-torso-down
  412: move-torso-up
  413: move-torso-interactive
  414: move-open-gripper
  415: move-close-gripper
  416: move-arm-interactive
  420: drive-to-docking-station
  421: drive-to-barkeeper-position
  422: drive-turn-left
  423: drive-turn-right
  424: drive-reverse
  425: drive-forward
  426: drive-here
  427: drive-follow-user
  430: order-glass-of-still-water
  431: order-glass-of-sparkling-water
  433: order-glass-of-tonic-water
  434: order-glass-of-bitter-lemon
  435: order-glass-of-bitter-orange
  436: order-glass-of-coca-cola
  437: order-glass-of-fanta
  440: order-glass-of-apple-juice
  441: order-glass-of-orange-juice
  442: order-glass-of-pineapple-juice
  450: order-glass-of-white-wine
  451: order-glass-of-red-wine
  452: order-glass-of-sangria
  460: order-glass-of-cuba-libre
  461: order-glass-of-tequila
  462: order-glass-of-tequila-sunrise
